# Generated by Django 3.2.12 on 2022-04-16 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "rut",
                    models.CharField(max_length=13, unique=True, verbose_name="rut"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("first_last_name", models.CharField(max_length=50)),
                ("second_last_name", models.CharField(max_length=50)),
                ("phone", models.CharField(max_length=13)),
                ("is_active", models.BooleanField(default=True)),
                ("admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
