# Generated by Django 3.2.12 on 2022-04-16 05:29

from django.db import migrations


def create_users(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    User = apps.get_model("users", "User")

    User.objects.create(
        email="alex.smith@example.com",
        name="Alex",
        first_last_name="Smith",
        second_last_name="Perez",
        is_active=True,
        admin=True,
        password="pbkdf2_sha256$260000$g1regTCJBgbdUOH2bCiimz$ru2cf4p59SWVqMCPP4DlaJCATxBG6JCjLoJ3GVZDN4s=",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
