# Generated by Django 3.2.13 on 2022-06-24 05:49

from django.contrib.auth.management import create_permissions
from django.db import migrations


def migrate_permissions(apps, schema_editor):
    # Since permissions aren't created at this time
    # we create them manually from the app config
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, apps=apps, verbosity=0)
        app_config.models_module = None


def add_habitant_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    permissions = {}
    permissions["parking"] = ["view"]
    permissions["announcement"] = ["view", "add", "change", "delete"]

    habitant_group = Group.objects.get(name="habitant")
    habitant_group.permissions.add(
        *[
            Permission.objects.get(codename="{}_{}".format(permission, app))
            for app in permissions.keys()
            for permission in permissions[app]
        ]
    )


def add_doorman_permissions(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")

    permissions = {}
    permissions["parking"] = ["view", "change"]
    permissions["visit"] = ["view", "add", "change", "delete"]

    doorman_group = Group.objects.get(name="doorman")
    doorman_group.permissions.add(
        *[
            Permission.objects.get(codename="{}_{}".format(permission, app))
            for app in permissions.keys()
            for permission in permissions[app]
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_create_groups"),
    ]

    operations = [
        migrations.RunPython(migrate_permissions, migrations.RunPython.noop),
        migrations.RunPython(add_habitant_permissions, migrations.RunPython.noop),
        migrations.RunPython(add_doorman_permissions, migrations.RunPython.noop),
    ]

