# Generated by Django 3.2.12 on 2022-06-07 22:10

import base.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13, verbose_name='rut')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('first_last_name', models.CharField(max_length=50, verbose_name='first last name')),
                ('second_last_name', models.CharField(max_length=50, verbose_name='second last name')),
                ('phone', models.CharField(max_length=13, verbose_name='phone')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('check_in', models.TimeField(default=django.utils.timezone.now, verbose_name='check in')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('desciption', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to=base.models.file_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
