# Generated by Django 3.2.13 on 2022-06-24 01:37

import base.models
import department.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='número')),
            ],
            options={
                'verbose_name': 'departamento',
                'verbose_name_plural': 'departamentos',
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=13, verbose_name='rut')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('first_last_name', models.CharField(max_length=50, verbose_name='primer apellido')),
                ('second_last_name', models.CharField(max_length=50, verbose_name='segundo apellido')),
                ('phone', models.CharField(max_length=13, verbose_name='telefono')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('check_in', models.TimeField(default=django.utils.timezone.now, verbose_name='hora de ingreso')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='department.department', verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'visita',
                'verbose_name_plural': 'visitas',
            },
        ),
        migrations.CreateModel(
            name='ValidationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=department.utils.create_validation_code, max_length=10, verbose_name='código')),
                ('status', models.CharField(choices=[('Available', 'Disponible'), ('Used', 'Usado')], max_length=10, verbose_name='estado')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_code', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'código de validación',
                'verbose_name_plural': 'códigos de validación',
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Free', 'Libre'), ('Occupied', 'Ocupado')], max_length=10, verbose_name='estado')),
                ('number', models.IntegerField(verbose_name='number de estacionamiento')),
                ('license_plate', models.CharField(blank=True, max_length=8, verbose_name='patente')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='department.department', verbose_name='departamento')),
            ],
            options={
                'verbose_name': 'estacionamiento',
                'verbose_name_plural': 'estacionamientos',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('title', models.CharField(max_length=255, verbose_name='titulo')),
                ('description', models.TextField(verbose_name='descripción')),
                ('image', models.ImageField(upload_to=base.models.file_path, verbose_name='imagen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'anuncio',
                'verbose_name_plural': 'anuncios',
            },
        ),
    ]
