# Generated by Django 3.1.1 on 2022-06-17 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_auto_20220616_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10, verbose_name='Status')),
                ('number', models.IntegerField(verbose_name='Parking space number')),
                ('license_plate', models.CharField(max_length=8, verbose_name='license plate')),
            ],
        ),
    ]
