# Generated by Django 3.1.1 on 2022-06-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='license_plate',
            field=models.CharField(blank=True, max_length=8, verbose_name='license plate'),
        ),
    ]
